name: airgo-project

services:
  airgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airgo_app
    image: airgo:latest
    network_mode: host
    environment:
      - GIN_MODE=release
      - PORT=8081
      - UPLOAD_PATH=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
