apiVersion: v1
kind: Service
metadata:
  name: airgo-service
  labels:
    app: airgo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30081
  selector:
    app: airgo
